server:
  port: 8080
  servlet:
    context-path: /api/v0.0.1
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cinema
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  flyway:
    enabled: true
    schemas: public
    locations: classpath:/migration
  mvc:
    throw-exception-if-no-handler-found: false


swagger:
  api:
    title: Ticket booking app
    description: Seat reservation system for a multiplex
    version: 1.0-SNAPSHOT
    controller:
      basepackage: pl.kubehe.cinema.application.rest
